language: java

group: reallybigindex

sudo: required

jdk:
  - oraclejdk8

script:
  - mvn clean package

app: spring-boot-tdd

deploy:
   provider: bluemixcloudfoundry
   skip_cleanup: true
   manifest: manifest.yml
   username: $BLUEMIX_USER
   password: $BLUEMIX_PASSWORD
   organization: $BLUEMIX_ORGANIZATION
   space: $BLUEMIX_SPACE
   api: https://api.ng.bluemix.net
   on:
      branch: master
