language: java

group: reallybigindex

sudo: required

jdk:
- oraclejdk8

script:
- mvn clean package

app: spring-boot-tdd

deploy:
  provider: script
  skip_cleanup: true
  script: python sample.py
  on:
    branch: master
